Repository showdownjs/showdown, pull requests merged in 2022-03, with the labels that each got.

#899 docs: added 'corporate' colors for docs
  docs/assets/extra.css
  mkdocs.yml
Labels: documentation

#900 docs: refactored installation to become quickstart guide
  docs/installation.md
  docs/quickstart.md
  mkdocs.yml
Labels: documentation

#709 add flexibility
  package-lock.json
  src/subParsers/makehtml/metadata.js
  test/functional/makehtml/cases/features/#709.allow-whitespaces-after-end-in-metadata.html
  test/functional/makehtml/cases/features/#709.allow-whitespaces-after-end-in-metadata.md
  test/functional/makehtml/testsuite.features.js
Labels: PR: request-changes

#688 feat(makemarkdown.table): support non-strict tables
  src/helpers.js
  src/subParsers/makemarkdown/table.js
  test/functional/makemarkdown/cases/standard/table-complex.html
  test/functional/makemarkdown/cases/standard/table-complex.md
  test/functional/makemarkdown/cases/standard/table-header-only.html
  test/functional/makemarkdown/cases/standard/table-header-only.md
  test/functional/makemarkdown/cases/standard/table-mix-malformed.html
  test/functional/makemarkdown/cases/standard/table-mix-malformed.md
  test/functional/makemarkdown/cases/standard/table-no-header.html
  test/functional/makemarkdown/cases/standard/table-no-header.md
  test/functional/makemarkdown/cases/standard/table-simple.html
  test/functional/makemarkdown/cases/standard/table-simple.md
Labels: PR: request-changes, scope:makeMarkdown
